services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VENDURE_SHOP_API_URL: https://vendure.shubash.me/shop-api
    ports:
      - "3000:3000"
    environment:
      VENDURE_SHOP_API_URL: https://vendure.shubash.me/shop-api
      NODE_ENV: production
      PORT: 3000
    restart: unless-stopped